In [1]:
import scanpy as sc

In [2]:
cbm2 = sc.read("cbm2_labeled.h5ad")

In [3]:
df = cbm2.to_df()

In [4]:
df

,4930570B17Rik,Abhd2,Acer3,Acta2,Adcy1,Adcy2,Adgrl3,Agt,Ahcyl2,Aif1l,...,Unc13b,Unc13c,Unc5c,Vim,Vip,Vps13c,Wdr17,Wfs1,Wipf3,Zfp36l1
cell_id,,,,,,,,,,,,,,,,,,,,,
2,0.0,0.000000,1.457261,1.599998,2.501454,0.840564,1.599998,4.019683,1.457261,0.506117,...,0.000000,1.457261,0.000000,0.000000,0.0,1.090752,0.000000,1.090752,1.290704,2.501454
4,0.0,0.000000,0.768798,0.000000,1.914840,0.000000,2.619502,0.000000,2.700425,0.000000,...,0.000000,0.768798,2.434888,0.000000,0.0,2.208296,0.000000,2.072294,0.000000,2.072294
10,0.0,3.566547,0.000000,1.240322,0.000000,0.000000,1.777230,2.261611,1.240322,0.000000,...,0.000000,1.965967,0.000000,2.586532,0.0,0.000000,0.000000,0.801267,0.000000,2.901261
12,0.0,1.125172,1.217283,0.910775,1.518855,0.260246,2.601540,2.323832,1.750242,0.260246,...,0.637502,0.637502,1.217283,0.466560,0.0,2.380401,0.783444,1.697219,1.023708,0.466560
14,0.0,2.014413,1.394168,0.623892,1.673517,1.005163,2.574631,0.000000,2.070579,0.000000,...,1.588785,0.000000,1.496203,0.832589,0.0,3.019887,1.152292,1.751626,1.496203,0.359832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4840191,0.0,3.139291,0.000000,0.000000,0.000000,0.000000,0.000000,3.810544,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
4840192,0.0,0.000000,0.000000,0.000000,1.602681,2.557149,0.000000,3.883540,0.000000,1.602681,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,2.825259,0.000000,0.000000
4840193,0.0,2.344111,0.000000,0.000000,0.000000,2.988103,2.344111,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,2.988103,0.000000,2.344111,0.000000,0.000000
4840194,0.0,2.427748,0.000000,4.295015,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.745575,0.0,0.000000,0.000000,0.000000,0.000000,3.075775
4840197,0.0,0.000000,0.000000,0.000000,3.465736,0.000000,0.000000,3.465736,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,2.803360

In [5]:
# df['celltype'] = cbm2.obs["MERFISH celltype"]
df

,4930570B17Rik,Abhd2,Acer3,Acta2,Adcy1,Adcy2,Adgrl3,Agt,Ahcyl2,Aif1l,...,Unc13b,Unc13c,Unc5c,Vim,Vip,Vps13c,Wdr17,Wfs1,Wipf3,Zfp36l1
cell_id,,,,,,,,,,,,,,,,,,,,,
2,0.0,0.000000,1.457261,1.599998,2.501454,0.840564,1.599998,4.019683,1.457261,0.506117,...,0.000000,1.457261,0.000000,0.000000,0.0,1.090752,0.000000,1.090752,1.290704,2.501454
4,0.0,0.000000,0.768798,0.000000,1.914840,0.000000,2.619502,0.000000,2.700425,0.000000,...,0.000000,0.768798,2.434888,0.000000,0.0,2.208296,0.000000,2.072294,0.000000,2.072294
10,0.0,3.566547,0.000000,1.240322,0.000000,0.000000,1.777230,2.261611,1.240322,0.000000,...,0.000000,1.965967,0.000000,2.586532,0.0,0.000000,0.000000,0.801267,0.000000,2.901261
12,0.0,1.125172,1.217283,0.910775,1.518855,0.260246,2.601540,2.323832,1.750242,0.260246,...,0.637502,0.637502,1.217283,0.466560,0.0,2.380401,0.783444,1.697219,1.023708,0.466560
14,0.0,2.014413,1.394168,0.623892,1.673517,1.005163,2.574631,0.000000,2.070579,0.000000,...,1.588785,0.000000,1.496203,0.832589,0.0,3.019887,1.152292,1.751626,1.496203,0.359832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4840191,0.0,3.139291,0.000000,0.000000,0.000000,0.000000,0.000000,3.810544,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
4840192,0.0,0.000000,0.000000,0.000000,1.602681,2.557149,0.000000,3.883540,0.000000,1.602681,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,2.825259,0.000000,0.000000
4840193,0.0,2.344111,0.000000,0.000000,0.000000,2.988103,2.344111,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,2.988103,0.000000,2.344111,0.000000,0.000000
4840194,0.0,2.427748,0.000000,4.295015,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.745575,0.0,0.000000,0.000000,0.000000,0.000000,3.075775
4840197,0.0,0.000000,0.000000,0.000000,3.465736,0.000000,0.000000,3.465736,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,2.803360

In [6]:
# df = df.iloc[:,-2:]

In [7]:
df

,4930570B17Rik,Abhd2,Acer3,Acta2,Adcy1,Adcy2,Adgrl3,Agt,Ahcyl2,Aif1l,...,Unc13b,Unc13c,Unc5c,Vim,Vip,Vps13c,Wdr17,Wfs1,Wipf3,Zfp36l1
cell_id,,,,,,,,,,,,,,,,,,,,,
2,0.0,0.000000,1.457261,1.599998,2.501454,0.840564,1.599998,4.019683,1.457261,0.506117,...,0.000000,1.457261,0.000000,0.000000,0.0,1.090752,0.000000,1.090752,1.290704,2.501454
4,0.0,0.000000,0.768798,0.000000,1.914840,0.000000,2.619502,0.000000,2.700425,0.000000,...,0.000000,0.768798,2.434888,0.000000,0.0,2.208296,0.000000,2.072294,0.000000,2.072294
10,0.0,3.566547,0.000000,1.240322,0.000000,0.000000,1.777230,2.261611,1.240322,0.000000,...,0.000000,1.965967,0.000000,2.586532,0.0,0.000000,0.000000,0.801267,0.000000,2.901261
12,0.0,1.125172,1.217283,0.910775,1.518855,0.260246,2.601540,2.323832,1.750242,0.260246,...,0.637502,0.637502,1.217283,0.466560,0.0,2.380401,0.783444,1.697219,1.023708,0.466560
14,0.0,2.014413,1.394168,0.623892,1.673517,1.005163,2.574631,0.000000,2.070579,0.000000,...,1.588785,0.000000,1.496203,0.832589,0.0,3.019887,1.152292,1.751626,1.496203,0.359832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4840191,0.0,3.139291,0.000000,0.000000,0.000000,0.000000,0.000000,3.810544,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
4840192,0.0,0.000000,0.000000,0.000000,1.602681,2.557149,0.000000,3.883540,0.000000,1.602681,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,2.825259,0.000000,0.000000
4840193,0.0,2.344111,0.000000,0.000000,0.000000,2.988103,2.344111,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,2.988103,0.000000,2.344111,0.000000,0.000000
4840194,0.0,2.427748,0.000000,4.295015,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.745575,0.0,0.000000,0.000000,0.000000,0.000000,3.075775
4840197,0.0,0.000000,0.000000,0.000000,3.465736,0.000000,0.000000,3.465736,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,2.803360

In [8]:
df["x_spatial"] = cbm2.obsm["X_spatial"][:,0]
df["y_spatial"] = cbm2.obsm["X_spatial"][:,1]

df["x_umap"] = cbm2.obsm["X_umap"][:,0]
df["y_umap"] = cbm2.obsm["X_umap"][:,1]

In [9]:
# df

In [10]:
# df = df.iloc[:, 1:]
df

,4930570B17Rik,Abhd2,Acer3,Acta2,Adcy1,Adcy2,Adgrl3,Agt,Ahcyl2,Aif1l,...,Vip,Vps13c,Wdr17,Wfs1,Wipf3,Zfp36l1,x_spatial,y_spatial,x_umap,y_umap
cell_id,,,,,,,,,,,,,,,,,,,,,
2,0.0,0.000000,1.457261,1.599998,2.501454,0.840564,1.599998,4.019683,1.457261,0.506117,...,0.0,1.090752,0.000000,1.090752,1.290704,2.501454,-124.680304,-1950.576081,5.577299,7.104292
4,0.0,0.000000,0.768798,0.000000,1.914840,0.000000,2.619502,0.000000,2.700425,0.000000,...,0.0,2.208296,0.000000,2.072294,0.000000,2.072294,-119.348309,-1869.341812,5.120703,11.320292
10,0.0,3.566547,0.000000,1.240322,0.000000,0.000000,1.777230,2.261611,1.240322,0.000000,...,0.0,0.000000,0.000000,0.801267,0.000000,2.901261,-100.198009,-1956.337967,0.451916,9.434436
12,0.0,1.125172,1.217283,0.910775,1.518855,0.260246,2.601540,2.323832,1.750242,0.260246,...,0.0,2.380401,0.783444,1.697219,1.023708,0.466560,-96.795866,-1971.059844,12.658809,19.168846
14,0.0,2.014413,1.394168,0.623892,1.673517,1.005163,2.574631,0.000000,2.070579,0.000000,...,0.0,3.019887,1.152292,1.751626,1.496203,0.359832,-90.441533,-1937.499672,12.779305,19.510969
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4840191,0.0,3.139291,0.000000,0.000000,0.000000,0.000000,0.000000,3.810544,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,35.811857,-2017.058611,6.800881,7.343563
4840192,0.0,0.000000,0.000000,0.000000,1.602681,2.557149,0.000000,3.883540,0.000000,1.602681,...,0.0,0.000000,0.000000,2.825259,0.000000,0.000000,-33.868878,-1901.404851,5.834416,7.222242
4840193,0.0,2.344111,0.000000,0.000000,0.000000,2.988103,2.344111,0.000000,0.000000,0.000000,...,0.0,2.988103,0.000000,2.344111,0.000000,0.000000,-28.116267,-1906.790554,11.746419,18.456478
4840194,0.0,2.427748,0.000000,4.295015,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,3.075775,57.850929,-1879.840399,1.584018,6.464273
4840197,0.0,0.000000,0.000000,0.000000,3.465736,0.000000,0.000000,3.465736,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,2.803360,43.475841,-1979.661088,6.974030,6.973606

In [11]:
merfish_celltype={
        "Corpus callosum oligo":"#dcf099",
        "L5 neurons":"#f5b914",
        "L1/2 neurons":"#f53855",
        "Thalamic neuron":"#a7f2ad",
        "L1 neurons":"#63a7ff",
        "GABAergic neurons":"#2e9ef5",
        "Striatal neurons":"#ffffff",
        "Cortical astrocyte":"#ff9412",
        "L2/3 neurons":"#8cfab1",
        "Cortical endothelial":"#f729b2",
        "Cortical oligos":"#fc5e9b",
        "Mature DG neurons":"#fff700",
        "Oligo sparse":"#96e78c",
        "Medial L1 Glutamatergic neurons":"#da08ff",
        "CA3 neurons":"#33ffeb",
        "Subventricular immature astrocytes":"#003cff",
        "L6 neurons":"#8cd5fa",
        "Upper thalamic neurons":"#ff9436",
        "L3 neurons":"#a86636",
        "Hippocampal astrocytes":"#19fa05",
        "Pericyte":"#ff0044",
        "Thalamic OPC":"#ff2471",
        "Thalamic oligo":"#a1b5f7",
        "Medial L2 neurons":"#bfff00",
        "Microglia sparse":"#fa6800",
        "Subpial endothelial cells":"#ffb300",
        "Ependymal cells":"#940000",
        "Thalamic endothelial":"#2c8a6a",
        "CA1 neurons":"#ff0000",
        "Nucleus of thalamus neurons":"#d61e24",
        "Progenitor cells":"#ff6600",
        "CA2 neurons":"#2fff00",
        "Astrocyte":"#9deaed",
        "Cortical sparse neurons":"#fe32ae",
        "Hippocampal/striatum endothelial":"#94ddf0",
        "Subpial mature astrocytes":"#ffeaba",
        "L4 neurons":"#44fa71",
        "Corpus callosum endothelial":"#fade5c",
        "Outer thalamic neurons":"#fad336",
        "Hypothalamic neurons":"#ff7aa9",
        "Medial L1 neurons":"#2cab79",
        "Sparse oligo":"#fb3bdc",
        "Outer thalamic oligo":"#e88cff",
        "Microglia corpus callosum":"#686ffc",
        "Striatal astrocyte":"#e719d0",
        "Striatal oligo":"#e2eda3",
        "Oligodendrocytes":"#00b8ff",
        "Sparse microglia":"#8606fb",
        "Endothelial sparse":"#da42e6",
        "Thalamic microglia":"#4af8f4",
        "Outer thalamic astrocyte":"#daa6ff",
        "Outer thalamic endothelial":"#c32cf6",
        "Upper thalamic astrocyte":"#daa6ff",
        "Interneuron":"#f6bd08",
        "Cortical GABAergic neuron":"#4a47e7",
        "Radial glia":"#5160f2",
        "Immature neurons":"#bb00ff",
        "Immature DG neurons":"#ff00d9",
        "New Cell Type":"#ff00d9"
        }

In [12]:
df['celltype'] = cbm2.obs["MERFISH celltype"]

In [13]:
df['color'] = df['celltype'].map(merfish_celltype)

In [14]:
df

,4930570B17Rik,Abhd2,Acer3,Acta2,Adcy1,Adcy2,Adgrl3,Agt,Ahcyl2,Aif1l,...,Wdr17,Wfs1,Wipf3,Zfp36l1,x_spatial,y_spatial,x_umap,y_umap,celltype,color
cell_id,,,,,,,,,,,,,,,,,,,,,
2,0.0,0.000000,1.457261,1.599998,2.501454,0.840564,1.599998,4.019683,1.457261,0.506117,...,0.000000,1.090752,1.290704,2.501454,-124.680304,-1950.576081,5.577299,7.104292,Thalamic OPC,#ff2471
4,0.0,0.000000,0.768798,0.000000,1.914840,0.000000,2.619502,0.000000,2.700425,0.000000,...,0.000000,2.072294,0.000000,2.072294,-119.348309,-1869.341812,5.120703,11.320292,Thalamic microglia,#4af8f4
10,0.0,3.566547,0.000000,1.240322,0.000000,0.000000,1.777230,2.261611,1.240322,0.000000,...,0.000000,0.801267,0.000000,2.901261,-100.198009,-1956.337967,0.451916,9.434436,Thalamic endothelial,#2c8a6a
12,0.0,1.125172,1.217283,0.910775,1.518855,0.260246,2.601540,2.323832,1.750242,0.260246,...,0.783444,1.697219,1.023708,0.466560,-96.795866,-1971.059844,12.658809,19.168846,Hypothalamic neurons,#ff7aa9
14,0.0,2.014413,1.394168,0.623892,1.673517,1.005163,2.574631,0.000000,2.070579,0.000000,...,1.152292,1.751626,1.496203,0.359832,-90.441533,-1937.499672,12.779305,19.510969,Hypothalamic neurons,#ff7aa9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4840191,0.0,3.139291,0.000000,0.000000,0.000000,0.000000,0.000000,3.810544,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,35.811857,-2017.058611,6.800881,7.343563,Oligo sparse,#96e78c
4840192,0.0,0.000000,0.000000,0.000000,1.602681,2.557149,0.000000,3.883540,0.000000,1.602681,...,0.000000,2.825259,0.000000,0.000000,-33.868878,-1901.404851,5.834416,7.222242,Thalamic OPC,#ff2471
4840193,0.0,2.344111,0.000000,0.000000,0.000000,2.988103,2.344111,0.000000,0.000000,0.000000,...,0.000000,2.344111,0.000000,0.000000,-28.116267,-1906.790554,11.746419,18.456478,Hypothalamic neurons,#ff7aa9
4840194,0.0,2.427748,0.000000,4.295015,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,3.075775,57.850929,-1879.840399,1.584018,6.464273,Subpial endothelial cells,#ffb300
4840197,0.0,0.000000,0.000000,0.000000,3.465736,0.000000,0.000000,3.465736,0.000000,0.000000,...,0.000000,0.000000,0.000000,2.803360,43.475841,-1979.661088,6.974030,6.973606,Astrocyte,#9deaed

In [15]:
# Define the new min and max values
new_min = -10
new_max = 10

# Calculate the current min and max values of the x_spatial column
min_value = df['x_spatial'].min()
max_value = df['x_spatial'].max()

# Normalize the x_spatial column to be between -10 and 10
df['x_spatial_norm'] = ((df['x_spatial'] - min_value) / (max_value - min_value)) * (new_max - new_min) + new_min

In [16]:
# Define the new min and max values
new_min = -10
new_max = 10

# Calculate the current min and max values of the x_spatial column
min_value = df['y_spatial'].min()
max_value = df['y_spatial'].max()

# Normalize the y_spatial column to be between -10 and 10
df['y_spatial_norm'] = ((df['y_spatial'] - min_value) / (max_value - min_value)) * (new_max - new_min) + new_min

In [17]:
# Define the new min and max values
new_min = -10
new_max = 10

# Calculate the current min and max values of the x_umap column
min_value = df['x_umap'].min()
max_value = df['x_umap'].max()

# Normalize the x_umap column to be between -10 and 10
df['x_umap_norm'] = ((df['x_umap'] - min_value) / (max_value - min_value)) * (new_max - new_min) + new_min

# Define the new min and max values
new_min = -10
new_max = 10

# Calculate the current min and max values of the x_umap column
min_value = df['y_umap'].min()
max_value = df['y_umap'].max()

# Normalize the y_umap column to be between -10 and 10
df['y_umap_norm'] = ((df['y_umap'] - min_value) / (max_value - min_value)) * (new_max - new_min) + new_min

In [18]:
cbm2

AnnData object with n_obs × n_vars = 57489 × 223
    obs: 'n_genes', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'leiden', 'Experiment', 'Age', 'Mouse', 'Section', 'Treatment', 'celltype', 'MERFISH celltype'
    var: 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts'
    uns: 'leiden', 'leiden_colors', 'neighbors', 'umap'
    obsm: 'X_pca', 'X_spatial', 'X_umap'
    obsp: 'connectivities', 'distances'

In [39]:
sc.tl.umap(cbm2, n_components=3)

/Users/kjenie/Programming/3js/.conda/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [19]:
df

,4930570B17Rik,Abhd2,Acer3,Acta2,Adcy1,Adcy2,Adgrl3,Agt,Ahcyl2,Aif1l,...,x_spatial,y_spatial,x_umap,y_umap,celltype,color,x_spatial_norm,y_spatial_norm,x_umap_norm,y_umap_norm
cell_id,,,,,,,,,,,,,,,,,,,,,
2,0.0,0.000000,1.457261,1.599998,2.501454,0.840564,1.599998,4.019683,1.457261,0.506117,...,-124.680304,-1950.576081,5.577299,7.104292,Thalamic OPC,#ff2471,1.021256,9.499300,-1.557493,-1.435267
4,0.0,0.000000,0.768798,0.000000,1.914840,0.000000,2.619502,0.000000,2.700425,0.000000,...,-119.348309,-1869.341812,5.120703,11.320292,Thalamic microglia,#4af8f4,1.039708,9.976083,-1.931914,2.002449
10,0.0,3.566547,0.000000,1.240322,0.000000,0.000000,1.777230,2.261611,1.240322,0.000000,...,-100.198009,-1956.337967,0.451916,9.434436,Thalamic endothelial,#2c8a6a,1.105980,9.465482,-5.760459,0.464725
12,0.0,1.125172,1.217283,0.910775,1.518855,0.260246,2.601540,2.323832,1.750242,0.260246,...,-96.795866,-1971.059844,12.658809,19.168846,Hypothalamic neurons,#ff7aa9,1.117754,9.379076,4.249555,8.402142
14,0.0,2.014413,1.394168,0.623892,1.673517,1.005163,2.574631,0.000000,2.070579,0.000000,...,-90.441533,-1937.499672,12.779305,19.510969,Hypothalamic neurons,#ff7aa9,1.139744,9.576048,4.348366,8.681108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4840191,0.0,3.139291,0.000000,0.000000,0.000000,0.000000,0.000000,3.810544,0.000000,0.000000,...,35.811857,-2017.058611,6.800881,7.343563,Oligo sparse,#96e78c,1.576661,9.109098,-0.554119,-1.240167
4840192,0.0,0.000000,0.000000,0.000000,1.602681,2.557149,0.000000,3.883540,0.000000,1.602681,...,-33.868878,-1901.404851,5.834416,7.222242,Thalamic OPC,#ff2471,1.335522,9.787898,-1.346649,-1.339090
4840193,0.0,2.344111,0.000000,0.000000,0.000000,2.988103,2.344111,0.000000,0.000000,0.000000,...,-28.116267,-1906.790554,11.746419,18.456478,Hypothalamic neurons,#ff7aa9,1.355429,9.756288,3.501369,7.821278
4840194,0.0,2.427748,0.000000,4.295015,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,57.850929,-1879.840399,1.584018,6.464273,Subpial endothelial cells,#ffb300,1.652931,9.914465,-4.832102,-1.957138
4840197,0.0,0.000000,0.000000,0.000000,3.465736,0.000000,0.000000,3.465736,0.000000,0.000000,...,43.475841,-1979.661088,6.974030,6.973606,Astrocyte,#9deaed,1.603184,9.328593,-0.412131,-1.541828

In [22]:
df["x_umap2"] = cbm2.obsm["X_umap"][:,0]
df["y_umap2"] = cbm2.obsm["X_umap"][:,1]
# df["z_umap2"] = cbm2.obsm["X_umap"][:,2]

In [23]:
# Define the new min and max values
new_min = -10
new_max = 10

# Calculate the current min and max values of the x_umap2 column
min_value = df['x_umap2'].min()
max_value = df['x_umap2'].max()

# Normalize the x_umap2 column to be between -10 and 10
df['x_umap2_norm'] = ((df['x_umap2'] - min_value) / (max_value - min_value)) * (new_max - new_min) + new_min

# Calculate the current min and max values of the x_umap2 column
min_value = df['y_umap2'].min()
max_value = df['y_umap2'].max()

# Normalize the y_umap2 column to be between -10 and 10
df['y_umap2_norm'] = ((df['y_umap2'] - min_value) / (max_value - min_value)) * (new_max - new_min) + new_min


# # Calculate the current min and max values of the x_umap2 column
# min_value = df['z_umap2'].min()
# max_value = df['z_umap2'].max()

# # Normalize the z_umap2 column to be between -10 and 10
# df['z_umap2_norm'] = ((df['z_umap2'] - min_value) / (max_value - min_value)) * (new_max - new_min) + new_min

In [25]:
df.to_csv("./cbm2_labeled.csv")

In [44]:
# Convert the DataFrame to JSON with 'records' orientation
json_data = df.to_json(orient='records')

# Specify the file path where you want to save the JSON afile
file_path = 'cbm2_labeled.json'

# Open the file in write mode and write the JSON data to it
with open(file_path, 'w') as json_file:
    json_file.write(json_data)

print(f'JSON data saved to {file_path}')

JSON data saved to cbm2_labeled.json

In [13]:
def normalize(data, new_min=-10, new_max=10):
    # Calculate the current min and max values of the x_spatial column
    min_value = data.min()
    max_value = data.max()

    # Normalize the x_spatial column to be between -10 and 10
    return ((data - min_value) / (max_value - min_value)) * (new_max - new_min) + new_min

In [53]:
def parse_json(adataa, filename, color_dict, group="MERFISH celltype", threed=False):
    adata = adataa.copy()
    df = adata.to_df()
    df['celltype'] = adata.obs[group]

    # df = df.iloc[:,-2:]

    df["x_spatial"] = adata.obsm["X_spatial"][:,0].tolist()
    df["y_spatial"] = adata.obsm["X_spatial"][:,1].tolist()


    if threed:
        sc.tl.umap(adata, n_components=3)
        df["z_umap"] = adata.obsm["X_umap"][:,2].tolist()
        df['z_umap_norm'] = normalize(df['z_umap'])

    df["x_umap"] = adata.obsm["X_umap"][:,0].tolist()
    df["y_umap"] = adata.obsm["X_umap"][:,1].tolist()

    df['x_umap_norm'] = normalize(df['x_umap'])
    df['y_umap_norm'] = normalize(df['y_umap'])

    # df = df.iloc[:, 1:]

    df['color'] = df['celltype'].map(color_dict)

    df['x_spatial_norm'] = normalize(df['x_spatial'])
    df['y_spatial_norm'] = normalize(df['y_spatial'])


    return df

    # Convert the DataFrame to JSON with 'records' orientation
    json_data = df.to_json(orient='records')

    # Specify the file path where you want to save the JSON afile
    file_path = f"{filename}"

    # Open the file in write mode and write the JSON data to it
    with open(file_path, 'w') as json_file:
        json_file.write(json_data)

    print(f'JSON data saved to {file_path}')

In [46]:
w4 = sc.read('./4_week_full_labeled_celltype.h5ad')
w4

/Users/kjenie/Programming/3js/.conda/lib/python3.10/site-packages/anndata/__init__.py:51: FutureWarning: `anndata.read` is deprecated, use `anndata.read_h5ad` instead. `ad.read` will be removed in mid 2024.
  warnings.warn(
/Users/kjenie/Programming/3js/.conda/lib/python3.10/site-packages/anndata/_core/anndata.py:1906: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 338443 × 275
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'tag', 'leiden', 'celltype'
    uns: 'leiden', 'leiden_colors', 'neighbors', 'umap'
    obsm: 'X_pca', 'X_raw', 'X_spatial', 'X_umap'
    obsp: 'connectivities', 'distances'

In [47]:
w4.obs.celltype.unique().tolist()

['Hippocampal endothelial',
 'Cortical oligodendrocytes',
 'Hippocampal CA1 neurons',
 'Hippocampal astrocytes',
 'L6 oligodendrocytes',
 'Dorsal stream endothelial',
 'SVZ astrocytes',
 'SVZ ependymal cells',
 'Fibertracts oligodendrocytes 2',
 'Cortical neurons',
 'Sparse oligodendrocytes',
 'Striatal oligodendrocytes',
 'Cortical & Hippocampal neurons (immature)',
 'Cortical endothelial',
 'Cortical micro PVM',
 'Fibertracts oligodendrocytes',
 'Hippocampal CA3 neurons',
 'L6 glutamatergic neurons',
 'L5/6 cortical neurons',
 'L5 neurons',
 'Astrocytes',
 'Striatal astrocytes',
 'Sparse astrocytes',
 'L2/3 cortical neurons',
 'L2/3 visual cortex neurons',
 'Retrospenial area neurons',
 'Striatal endothelial',
 'Sparse neurons (immature)',
 'Pia matter',
 'L1 neurons',
 'Sparse endothlial',
 'L1 anterior olfactory nucleus astrocytes',
 'Reticular nucleus neurons',
 'Subiculum neurons',
 'Sparse micro PVM',
 'Inferior colliculus neurons',
 'Dentate gyrus neurons',
 'Dentate gyrus immature neurons',
 'Lateral preoptic oligodendrocytes',
 'Thalamic endothelial',
 'Thalamic neurons',
 'Thalamic oligodendrocytes',
 'Thalamic neurons 2',
 'Thalamic oligodendrocytes 3',
 'Superior colliculus neurons',
 'Brain stem astrocytes',
 'Fibertracts oligodendrocytes 3',
 'Sparse oligodendrocytes 2',
 'Ventral posteromedial nucleus oligodendrocytes',
 'Brain stem endothelial',
 'Brain stem oligodendrocytes',
 'Sparse neurons',
 'Pallidum neurons',
 'Thalamic oligodendrocytes 2',
 'Oligodendrocytes (artifact)',
 'Brain stem astrocytes 2',
 'Cerebellar molecular layer neurons',
 'Medulla neurons',
 'Medullary reticular nucleus astrocytes',
 'Cerebellar granular neurons',
 'Sst neurons',
 'L2/3 somatomotor neurons',
 'Striatal neurons 2',
 'Striatal neurons 3',
 'Endopiriform nucleus, dorsal-part neurons',
 'Pons neurons',
 'Brain stem oligodendrocytes (astrocytic)',
 'Cerebellar fibertract oligodendrocytes',
 'Medulla fibertract astrocytes',
 'Substantia nigra astrocytes',
 'Olfactory tubercle neurons',
 'Nucleus accumbens neurons',
 'Striatal neurons 4',
 'Striatal neurons',
 'Olfactory bulb plexiform neurons',
 'Choroid plexus',
 'Cerebellar granular neurons 2',
 'Olfactory immature neurons',
 'L2 anterior olfactory nucleus neurons',
 'Superior vestibular nucleus',
 'Olfactory bulb GABAergic granule neurons',
 'Olfactory bulb glomerular neurons',
 'Olfactory bulb fibertract astrocytes',
 'Olfactory bulb immature neurons']

In [48]:
week4_celltype = {
    "Artifact": "#ffffff",
    "Artifact 1": "#01FDC2",
    "Artifact 2": "#E0720D",
    "Artifact 3": "#E0720D",
    "Artifact 4": "#E0720D",
    "Artifact 5": "#66BF2E",
    "Artifact 6": "#E3F098",
    "Artifact 7": "#E09C0B",
    "Artifact 8": "#E0990B",
    "Artifact 9": "#A8C920",
    "Artifact 10": "#E3F098",
    "Artifact 11": "#00FFC3",
    "Artifact 12": "#F49E43",
    "Artifact 13": "#004D98",
    "Artifact 14": "#2F59F5",
    "Astrocytes": "#fa4dd2",
    "Brain stem astrocytes": "#1ce5ff",
    "Brain stem astrocytes 2": "#217eff",
    "Brain stem endothelial": "#41fa75",
    "Brain stem oligodendrocytes": "#c4f013",
    "Brain stem oligodendrocytes (astrocytic)": "#e3a820",
    "Choroid plexus": "#940000",
    "Cerebellar fibertract oligodendrocytes": "#DB0030",
    "Cerebellar granular neurons": "#004D98",
    "Cerebellar granular neurons 2": "#FFED02",
    "Cerebellar molecular layer neurons": "#A50044",
    "Cortical & Hippocampal neurons (immature)": "#b57f85",
    "Cortical endothelial": "#75fa9b",
    "Cortical micro PVM": "#f00768",
    "Cortical neurons": "#faaa39",
    "Cortical oligodendrocytes": "#f0ec13",
    "Dentate gyrus immature neurons": "#FF00D9",
    "Dentate gyrus neurons": "#FFF700",
    "Dorsal stream endothelial": "#0fbf76",
    "Endopiriform nucleus, dorsal-part neurons": "#e61037",
    "Fibertracts oligodendrocytes": "#788a08",
    "Fibertracts oligodendrocytes 2": "#aec236",
    "Fibertracts oligodendrocytes 3": "#e2f092",
    "Hippocampal astrocytes": "#0d0dd4",
    "Hippocampal CA1 neurons": "#00ff7b",
    "Hippocampal CA3 neurons": "#33FFEB",
    "Hippocampal endothelial": "#caf0b1",
    "Inferior colliculus neurons": "#d380ff",
    "L1 anterior olfactory nucleus astrocytes": "#8799de",
    "L1 neurons": "#63A7FF",
    "L2/3 cortical neurons": "#6323fa",
    "L2/3 somatomotor neurons": "#F53855",
    "L2/3 visual cortex neurons": "#8CFAB1",
    "L2 anterior olfactory nucleus neurons": "#de8787",
    "L5/6 cortical neurons": "#2CAB79",
    "L5 neurons": "#8CD5FA",
    "L6 glutamatergic neurons": "#e0990b",
    "L6 oligodendrocytes": "#67c22f",
    "Lateral preoptic oligodendrocytes": "#0bdea2",
    "Medulla fibertract astrocytes": "#5040ff",
    "Medulla neurons": "#d1048d",
    "Medullary reticular nucleus astrocytes": "#77c7fc",
    "Nucleus accumbens neurons": "#ff6854",
    "Olfactory bulb fibertract astrocytes": "#fffc3b",
    "Olfactory bulb GABAergic granule neurons": "#faa716",
    "Olfactory bulb glomerular neurons": "#fa3116",
    "Olfactory bulb immature neurons": "#c73be3",
    "Olfactory bulb plexiform neurons": "#daffb0",
    "Oligodendrocytes (artifact)": "#f05179",
    "Olfactory immature neurons": "#5500ff",
    "Olfactory tubercle neurons": "#ffee00",
    "Pallidum neurons": "#ff00d4",
    "Pia matter": "#ffffff",
    "Pons neurons": "#fc0d85",
    "Reticular nucleus neurons": "#64ed68",
    "Retrospenial area neurons": "#ff4b19",
    "Sparse astrocytes": "#87bbff",
    "Sparse endothlial": "#87ffbd",
    "Sparse micro PVM": "#dfff87",
    "Sparse neurons": "#ff8795",
    "Sparse neurons (immature)": "#d387ff",
    "Sparse oligodendrocytes": "#ffc187",
    "Sparse oligodendrocytes 2": "#a8c920",
    "Striatal astrocytes": "#5975ff",
    "Striatal endothelial": "#3cc920",
    "Striatal neurons": "#ff7db5",
    "Striatal neurons 2": "#7dc9ff",
    "Striatal neurons 3": "#ffdf7d",
    "Striatal neurons 4": "#8aff7d",
    "Striatal oligodendrocytes": "#00ffc3",
    "Subiculum neurons": "#ff0fc3",
    "Substantia nigra astrocytes": "#996eff",
    "Superior colliculus neurons": "#ff9a75",
    "Superior vestibular nucleus": "#a821de",
    "SVZ astrocytes": "#e6172f",
    "SVZ ependymal cells": "#FF9436",
    "Sst neurons": "#1cffe1",
    "Thalamic endothelial": "#76bf65",
    "Thalamic neurons": "#2f59f5",
    "Thalamic neurons 2": "#f5952f",
    "Thalamic oligodendrocytes": "#4495f2",
    "Thalamic oligodendrocytes 2": "#f5f06e",
    "Thalamic oligodendrocytes 3": "#ff9021",
    "Ventral posteromedial nucleus oligodendrocytes": "#9eff4f"
}

In [49]:
w4.obs.tag

1          DCBBL1_4week_6_2_2023_set1
2          DCBBL1_4week_6_2_2023_set1
3          DCBBL1_4week_6_2_2023_set1
4          DCBBL1_4week_6_2_2023_set1
5          DCBBL1_4week_6_2_2023_set1
                      ...
4700867    DCBBL1_4week_6_2_2023_set3
4700881    DCBBL1_4week_6_2_2023_set3
4700885    DCBBL1_4week_6_2_2023_set3
4700895    DCBBL1_4week_6_2_2023_set3
4700896    DCBBL1_4week_6_2_2023_set3
Name: tag, Length: 338443, dtype: category
Categories (3, object): ['DCBBL1_4week_6_2_2023_set1', 'DCBBL1_4week_6_2_2023_set2', 'DCBBL1_4week_6_2_2023_set3']

In [50]:
w41 = w4[w4.obs["tag"] == "DCBBL1_4week_6_2_2023_set1"]

In [51]:
w41

View of AnnData object with n_obs × n_vars = 269928 × 275
    obs: 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'tag', 'leiden', 'celltype'
    uns: 'leiden', 'leiden_colors', 'neighbors', 'umap'
    obsm: 'X_pca', 'X_raw', 'X_spatial', 'X_umap'
    obsp: 'connectivities', 'distances'

In [52]:
w41.obsm["X_spatial"][:,0]

ArrayView([ 24.052383,  27.690826,  37.94915 , ..., 458.1147  ,
           516.0262  , 339.46408 ], dtype=float32)

In [54]:
df = parse_json(w41, "4_week_full_labeled_celltype2.json", color_dict=week4_celltype, group="celltype", threed=False)

In [55]:
df

,Abhd2,Acer3,Acta2,Actb,Actg1,Adarb2,Adcy1,Adcy2,Adgrl3,Agt,...,celltype,x_spatial,y_spatial,x_umap,y_umap,x_umap_norm,y_umap_norm,color,x_spatial_norm,y_spatial_norm
1,1.393940,0.000000,0.000000,3.838603,2.311754,1.954644,3.838603,0.000000,2.574352,0.000000,...,Hippocampal endothelial,24.052383,253.799500,10.482393,-2.780853,2.582405,-2.852203,#caf0b1,5.194164,0.249285
2,1.065584,0.322451,0.565889,3.332775,2.762523,0.925063,3.319100,1.188770,2.352581,1.645880,...,Cortical oligodendrocytes,27.690826,168.267990,11.721458,-2.936887,3.658803,-3.019196,#f0ec13,5.205497,0.121040
3,0.663088,0.663088,0.000000,4.257277,3.524216,1.058329,3.374966,0.663088,2.508730,0.000000,...,Hippocampal CA1 neurons,37.949150,45.320992,16.279911,-6.120666,7.618812,-6.426593,#00ff7b,5.237449,-0.063305
4,0.832950,0.000000,0.000000,3.867096,3.295907,0.832950,3.720933,1.824610,3.081979,0.000000,...,Hippocampal CA1 neurons,54.633976,65.764610,16.322729,-6.124500,7.656009,-6.430697,#00ff7b,5.289418,-0.032652
5,1.169960,0.315038,0.554242,3.557306,2.783945,1.047864,3.346495,0.747130,2.253095,1.548223,...,Hippocampal astrocytes,59.947510,154.458542,11.702301,-2.747996,3.642161,-2.817038,#0d0dd4,5.305968,0.100335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69700865,1.977578,0.000000,0.000000,2.979383,4.043525,0.000000,4.147131,0.000000,2.979383,0.000000,...,Sparse oligodendrocytes,555.099243,147.856094,10.156709,-4.555894,2.299477,-4.751917,#ffc187,6.848234,0.090435
69700887,2.188270,0.000000,0.000000,3.796808,2.555649,0.000000,2.555649,0.000000,2.188270,0.000000,...,L6 oligodendrocytes,412.016266,274.510193,8.990659,0.688176,1.286509,0.860481,#67c22f,6.402569,0.280338
69700898,0.000000,0.000000,0.000000,3.801622,2.983669,0.000000,3.258619,1.981469,2.603192,0.000000,...,L6 oligodendrocytes,458.114685,283.577423,8.984583,0.558896,1.281231,0.722121,#67c22f,6.546153,0.293934
69700907,2.170658,0.000000,0.000000,4.260938,2.170658,0.000000,2.805061,0.000000,0.000000,0.000000,...,Cortical endothelial,516.026184,299.958313,9.820981,-3.423995,2.007825,-3.540516,#75fa9b,6.726532,0.318495
69700921,2.443173,1.833342,0.000000,3.631866,3.091906,0.000000,3.305925,0.000000,0.000000,0.000000,...,SVZ ependymal cells,339.464081,235.650909,8.563160,-1.855570,0.915133,-1.861930,#FF9436,6.176588,0.222073

In [56]:
# Convert the DataFrame to JSON with 'records' orientation
json_data = df.to_json(orient='records')

# Specify the file path where you want to save the JSON afile
file_path = f"4weeks_genes.json"

# Open the file in write mode and write the JSON data to it
with open(file_path, 'w') as json_file:
    json_file.write(json_data)

print(f'JSON data saved to {file_path}')

JSON data saved to 4weeks_genes.json

In [28]:
adata = w41
filename = "4_week_full_labeled_celltype.json"
color_dict=week4_celltype
group="celltype"

df = adata.to_df()
df['celltype'] = adata.obs[group]

df = df.iloc[:,-2:]

df["x_spatial"] = adata.obsm["X_spatial"][:,0]
df["y_spatial"] = adata.obsm["X_spatial"][:,1]

df["x_umap"] = adata.obsm["X_umap"][:,0]
df["y_umap"] = adata.obsm["X_umap"][:,1]

# df = df.iloc[:, 1:]

# df['color'] = df['celltype'].map(color_dict)

# df['x_spatial_norm'] = normalize(df['x_spatial'])
# df['y_spatial_norm'] = normalize(df['y_spatial'])

# df['x_umap_norm'] = normalize(df['x_umap'])
# df['y_umap_norm'] = normalize(df['y_umap'])

# # Convert the DataFrame to JSON with 'records' orientation
# json_data = df.to_json(orient='records')

# # Specify the file path where you want to save the JSON afile
# file_path = f"{filename}"

# # Open the file in write mode and write the JSON data to it
# with open(file_path, 'w') as json_file:
#     json_file.write(json_data)

# print(f'JSON data saved to {file_path}')

In [29]:
df

,Zfp36l1,celltype,x_spatial,y_spatial,x_umap,y_umap
1,2.782137,Hippocampal endothelial,NaN,NaN,NaN,NaN
2,2.152940,Cortical oligodendrocytes,NaN,NaN,NaN,NaN
3,0.000000,Hippocampal CA1 neurons,NaN,NaN,NaN,NaN
4,1.280986,Hippocampal CA1 neurons,NaN,NaN,NaN,NaN
5,1.466213,Hippocampal astrocytes,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
69700865,0.000000,Sparse oligodendrocytes,NaN,NaN,NaN,NaN
69700887,0.000000,L6 oligodendrocytes,NaN,NaN,NaN,NaN
69700898,0.000000,L6 oligodendrocytes,NaN,NaN,NaN,NaN
69700907,0.000000,Cortical endothelial,NaN,NaN,NaN,NaN
69700921,3.091906,SVZ ependymal cells,NaN,NaN,NaN,NaN

In [34]:
df["x_spatial2"] = adata.obsm["X_spatial"][:,0].tolist()
df

,Zfp36l1,celltype,x_spatial,y_spatial,x_umap,y_umap,x_spatial2
1,2.782137,Hippocampal endothelial,NaN,NaN,NaN,NaN,24.052383
2,2.152940,Cortical oligodendrocytes,NaN,NaN,NaN,NaN,27.690826
3,0.000000,Hippocampal CA1 neurons,NaN,NaN,NaN,NaN,37.949150
4,1.280986,Hippocampal CA1 neurons,NaN,NaN,NaN,NaN,54.633976
5,1.466213,Hippocampal astrocytes,NaN,NaN,NaN,NaN,59.947510
...,...,...,...,...,...,...,...
69700865,0.000000,Sparse oligodendrocytes,NaN,NaN,NaN,NaN,555.099243
69700887,0.000000,L6 oligodendrocytes,NaN,NaN,NaN,NaN,412.016266
69700898,0.000000,L6 oligodendrocytes,NaN,NaN,NaN,NaN,458.114685
69700907,0.000000,Cortical endothelial,NaN,NaN,NaN,NaN,516.026184
69700921,3.091906,SVZ ependymal cells,NaN,NaN,NaN,NaN,339.464081